"""Initial migration2

Revision ID: 705dad79a856
Revises: 9fc71adfde97
Create Date: 2025-11-02 17:49:15.878838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705dad79a856'
down_revision: Union[str, Sequence[str], None] = '9fc71adfde97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'stations', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'station_id')
    # ### end Alembic commands ###
